//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_quan_ly_ton_giao.ThongKe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThongKe.ThongKeSoap")]
    public interface ThongKeSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        service_quan_ly_ton_giao.ThongKe.HelloWorldResponse HelloWorld(service_quan_ly_ton_giao.ThongKe.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<service_quan_ly_ton_giao.ThongKe.HelloWorldResponse> HelloWorldAsync(service_quan_ly_ton_giao.ThongKe.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public service_quan_ly_ton_giao.ThongKe.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(service_quan_ly_ton_giao.ThongKe.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public service_quan_ly_ton_giao.ThongKe.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(service_quan_ly_ton_giao.ThongKe.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThongKeSoapChannel : service_quan_ly_ton_giao.ThongKe.ThongKeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThongKeSoapClient : System.ServiceModel.ClientBase<service_quan_ly_ton_giao.ThongKe.ThongKeSoap>, service_quan_ly_ton_giao.ThongKe.ThongKeSoap {
        
        public ThongKeSoapClient() {
        }
        
        public ThongKeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThongKeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThongKeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThongKeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        service_quan_ly_ton_giao.ThongKe.HelloWorldResponse service_quan_ly_ton_giao.ThongKe.ThongKeSoap.HelloWorld(service_quan_ly_ton_giao.ThongKe.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            service_quan_ly_ton_giao.ThongKe.HelloWorldRequest inValue = new service_quan_ly_ton_giao.ThongKe.HelloWorldRequest();
            inValue.Body = new service_quan_ly_ton_giao.ThongKe.HelloWorldRequestBody();
            service_quan_ly_ton_giao.ThongKe.HelloWorldResponse retVal = ((service_quan_ly_ton_giao.ThongKe.ThongKeSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<service_quan_ly_ton_giao.ThongKe.HelloWorldResponse> service_quan_ly_ton_giao.ThongKe.ThongKeSoap.HelloWorldAsync(service_quan_ly_ton_giao.ThongKe.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<service_quan_ly_ton_giao.ThongKe.HelloWorldResponse> HelloWorldAsync() {
            service_quan_ly_ton_giao.ThongKe.HelloWorldRequest inValue = new service_quan_ly_ton_giao.ThongKe.HelloWorldRequest();
            inValue.Body = new service_quan_ly_ton_giao.ThongKe.HelloWorldRequestBody();
            return ((service_quan_ly_ton_giao.ThongKe.ThongKeSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
