//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_quan_ly_ton_giao.tblCoSo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tblCoSo.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDLCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemDLCoSo(string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDLCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemDLCoSoAsync(string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaDLCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SuaDLCoSo(int IDCoSo, string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaDLCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SuaDLCoSoAsync(int IDCoSo, string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaLogicDLCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaLogicDLCoSo(int IDCoSo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaLogicDLCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaLogicDLCoSoAsync(int IDCoSo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HienThiDSCoSo(string dieukien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSCoSoAsync(string dieukien);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : service_quan_ly_ton_giao.tblCoSo.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<service_quan_ly_ton_giao.tblCoSo.WebServiceSoap>, service_quan_ly_ton_giao.tblCoSo.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ThemDLCoSo(string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi) {
            return base.Channel.ThemDLCoSo(TenCoSo, DiaChi, NguoiQuanLy, HinhAnh, IDToChuc, GioiThieu, ChucNang, DaXoa, TenThuongGoi);
        }
        
        public System.Threading.Tasks.Task<int> ThemDLCoSoAsync(string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi) {
            return base.Channel.ThemDLCoSoAsync(TenCoSo, DiaChi, NguoiQuanLy, HinhAnh, IDToChuc, GioiThieu, ChucNang, DaXoa, TenThuongGoi);
        }
        
        public int SuaDLCoSo(int IDCoSo, string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi) {
            return base.Channel.SuaDLCoSo(IDCoSo, TenCoSo, DiaChi, NguoiQuanLy, HinhAnh, IDToChuc, GioiThieu, ChucNang, DaXoa, TenThuongGoi);
        }
        
        public System.Threading.Tasks.Task<int> SuaDLCoSoAsync(int IDCoSo, string TenCoSo, int DiaChi, int NguoiQuanLy, string HinhAnh, int IDToChuc, string GioiThieu, int ChucNang, int DaXoa, string TenThuongGoi) {
            return base.Channel.SuaDLCoSoAsync(IDCoSo, TenCoSo, DiaChi, NguoiQuanLy, HinhAnh, IDToChuc, GioiThieu, ChucNang, DaXoa, TenThuongGoi);
        }
        
        public int XoaLogicDLCoSo(int IDCoSo) {
            return base.Channel.XoaLogicDLCoSo(IDCoSo);
        }
        
        public System.Threading.Tasks.Task<int> XoaLogicDLCoSoAsync(int IDCoSo) {
            return base.Channel.XoaLogicDLCoSoAsync(IDCoSo);
        }
        
        public System.Data.DataTable HienThiDSCoSo(string dieukien) {
            return base.Channel.HienThiDSCoSo(dieukien);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSCoSoAsync(string dieukien) {
            return base.Channel.HienThiDSCoSoAsync(dieukien);
        }
    }
}
