//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_quan_ly_ton_giao.tblToChucQuanTri {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tblToChucQuanTri.tblToChucQuanTriSoap")]
    public interface tblToChucQuanTriSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDLToChuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemDLToChuc(string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemDLToChuc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemDLToChucAsync(string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaDLToChuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SuaDLToChuc(int IDToChuc, string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SuaDLToChuc", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SuaDLToChucAsync(int IDToChuc, string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaLogicDLCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaLogicDLCoSo(int IDToChuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaLogicDLCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaLogicDLCoSoAsync(int IDToChuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSToChucQuanTri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HienThiDSToChucQuanTri(string dieukien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSToChucQuanTri", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSToChucQuanTriAsync(string dieukien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoIDToChuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TaoIDToChuc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoIDToChuc", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TaoIDToChucAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaCoSotblTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaCoSotblTinDo(string TenToChuc, string TenTonGiao, string DieuKien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaCoSotblTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaCoSotblTinDoAsync(string TenToChuc, string TenTonGiao, string DieuKien);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tblToChucQuanTriSoapChannel : service_quan_ly_ton_giao.tblToChucQuanTri.tblToChucQuanTriSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tblToChucQuanTriSoapClient : System.ServiceModel.ClientBase<service_quan_ly_ton_giao.tblToChucQuanTri.tblToChucQuanTriSoap>, service_quan_ly_ton_giao.tblToChucQuanTri.tblToChucQuanTriSoap {
        
        public tblToChucQuanTriSoapClient() {
        }
        
        public tblToChucQuanTriSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tblToChucQuanTriSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblToChucQuanTriSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblToChucQuanTriSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ThemDLToChuc(string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh) {
            return base.Channel.ThemDLToChuc(TenToChuc, IDTonGiao, GioiThieu, HinhAnh);
        }
        
        public System.Threading.Tasks.Task<int> ThemDLToChucAsync(string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh) {
            return base.Channel.ThemDLToChucAsync(TenToChuc, IDTonGiao, GioiThieu, HinhAnh);
        }
        
        public int SuaDLToChuc(int IDToChuc, string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh) {
            return base.Channel.SuaDLToChuc(IDToChuc, TenToChuc, IDTonGiao, GioiThieu, HinhAnh);
        }
        
        public System.Threading.Tasks.Task<int> SuaDLToChucAsync(int IDToChuc, string TenToChuc, int IDTonGiao, string GioiThieu, string HinhAnh) {
            return base.Channel.SuaDLToChucAsync(IDToChuc, TenToChuc, IDTonGiao, GioiThieu, HinhAnh);
        }
        
        public int XoaLogicDLCoSo(int IDToChuc) {
            return base.Channel.XoaLogicDLCoSo(IDToChuc);
        }
        
        public System.Threading.Tasks.Task<int> XoaLogicDLCoSoAsync(int IDToChuc) {
            return base.Channel.XoaLogicDLCoSoAsync(IDToChuc);
        }
        
        public System.Data.DataTable HienThiDSToChucQuanTri(string dieukien) {
            return base.Channel.HienThiDSToChucQuanTri(dieukien);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSToChucQuanTriAsync(string dieukien) {
            return base.Channel.HienThiDSToChucQuanTriAsync(dieukien);
        }
        
        public System.Data.DataTable TaoIDToChuc() {
            return base.Channel.TaoIDToChuc();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TaoIDToChucAsync() {
            return base.Channel.TaoIDToChucAsync();
        }
        
        public int XoaCoSotblTinDo(string TenToChuc, string TenTonGiao, string DieuKien) {
            return base.Channel.XoaCoSotblTinDo(TenToChuc, TenTonGiao, DieuKien);
        }
        
        public System.Threading.Tasks.Task<int> XoaCoSotblTinDoAsync(string TenToChuc, string TenTonGiao, string DieuKien) {
            return base.Channel.XoaCoSotblTinDoAsync(TenToChuc, TenTonGiao, DieuKien);
        }
    }
}
