//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_quan_ly_ton_giao.tblTinDo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tblTinDo.tblTinDoSoap")]
    public interface tblTinDoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HienThiDSTinDo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSTinDoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ThemTinDo(
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThemTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ThemTinDoAsync(
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int XoaTinDo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XoaTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> XoaTinDoAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DuLieuTinh", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DuLieuTinh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DuLieuTinh", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DuLieuTinhAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TruyVanTenHuyen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TruyVanTenHuyen(string tinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TruyVanTenHuyen", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TruyVanTenHuyenAsync(string tinh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TruyVanTenXa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable TruyVanTenXa(string huyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TruyVanTenXa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> TruyVanTenXaAsync(string huyen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdQueQuan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdQueQuan(string tinh, string huyen, string xa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdQueQuan", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IdQueQuanAsync(string tinh, string huyen, string xa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdDiaChi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdDiaChi(string tinh, string huyen, string xa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdDiaChi", ReplyAction="*")]
        System.Threading.Tasks.Task<string> IdDiaChiAsync(string tinh, string huyen, string xa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdChucSac", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IdChucSac(string tenChucSac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdChucSac", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IdChucSacAsync(string tenChucSac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdCoSo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IdCoSo(string tenCoSo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdCoSo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IdCoSoAsync(string tenCoSo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdChucVu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IdChucVu(string tenChucVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdChucVu", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IdChucVuAsync(string tenChucVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OneRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable OneRecord(string tblBang, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OneRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> OneRecordAsync(string tblBang, string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTonGiao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IDTonGiao(string tenTonGiao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDTonGiao", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IDTonGiaoAsync(string tenTonGiao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDiaChi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayDiaChi(string idxa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayDiaChi", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayDiaChiAsync(string idxa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayGiaTriDon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object LayGiaTriDon(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayGiaTriDon", ReplyAction="*")]
        System.Threading.Tasks.Task<object> LayGiaTriDonAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMotBang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LayMotBang(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayMotBang", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LayMotBangAsync(string sqlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateTinDo(
                    string idTinDo, 
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateTinDoAsync(
                    string idTinDo, 
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tblTinDoSoapChannel : service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tblTinDoSoapClient : System.ServiceModel.ClientBase<service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap>, service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap {
        
        public tblTinDoSoapClient() {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblTinDoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable HienThiDSTinDo() {
            return base.Channel.HienThiDSTinDo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSTinDoAsync() {
            return base.Channel.HienThiDSTinDoAsync();
        }
        
        public int ThemTinDo(
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu) {
            return base.Channel.ThemTinDo(phapDanh, hodemTheDanh, tenTheDanh, ngaySinh, gioiTinh, danToc, queQuan, diaChi, taiChinh, sucKhoe, tcTichCuc, tcNguyHiem, hinhAnh, matDoi, matDao, hdCaNhan, hdToChuc, idChucSac, idCoSo, daXoa, ngayVaoTonGiao, idChucVu);
        }
        
        public System.Threading.Tasks.Task<int> ThemTinDoAsync(
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu) {
            return base.Channel.ThemTinDoAsync(phapDanh, hodemTheDanh, tenTheDanh, ngaySinh, gioiTinh, danToc, queQuan, diaChi, taiChinh, sucKhoe, tcTichCuc, tcNguyHiem, hinhAnh, matDoi, matDao, hdCaNhan, hdToChuc, idChucSac, idCoSo, daXoa, ngayVaoTonGiao, idChucVu);
        }
        
        public int XoaTinDo(int Id) {
            return base.Channel.XoaTinDo(Id);
        }
        
        public System.Threading.Tasks.Task<int> XoaTinDoAsync(int Id) {
            return base.Channel.XoaTinDoAsync(Id);
        }
        
        public System.Data.DataTable DuLieuTinh() {
            return base.Channel.DuLieuTinh();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DuLieuTinhAsync() {
            return base.Channel.DuLieuTinhAsync();
        }
        
        public System.Data.DataTable TruyVanTenHuyen(string tinh) {
            return base.Channel.TruyVanTenHuyen(tinh);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TruyVanTenHuyenAsync(string tinh) {
            return base.Channel.TruyVanTenHuyenAsync(tinh);
        }
        
        public System.Data.DataTable TruyVanTenXa(string huyen) {
            return base.Channel.TruyVanTenXa(huyen);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TruyVanTenXaAsync(string huyen) {
            return base.Channel.TruyVanTenXaAsync(huyen);
        }
        
        public string IdQueQuan(string tinh, string huyen, string xa) {
            return base.Channel.IdQueQuan(tinh, huyen, xa);
        }
        
        public System.Threading.Tasks.Task<string> IdQueQuanAsync(string tinh, string huyen, string xa) {
            return base.Channel.IdQueQuanAsync(tinh, huyen, xa);
        }
        
        public string IdDiaChi(string tinh, string huyen, string xa) {
            return base.Channel.IdDiaChi(tinh, huyen, xa);
        }
        
        public System.Threading.Tasks.Task<string> IdDiaChiAsync(string tinh, string huyen, string xa) {
            return base.Channel.IdDiaChiAsync(tinh, huyen, xa);
        }
        
        public int IdChucSac(string tenChucSac) {
            return base.Channel.IdChucSac(tenChucSac);
        }
        
        public System.Threading.Tasks.Task<int> IdChucSacAsync(string tenChucSac) {
            return base.Channel.IdChucSacAsync(tenChucSac);
        }
        
        public int IdCoSo(string tenCoSo) {
            return base.Channel.IdCoSo(tenCoSo);
        }
        
        public System.Threading.Tasks.Task<int> IdCoSoAsync(string tenCoSo) {
            return base.Channel.IdCoSoAsync(tenCoSo);
        }
        
        public int IdChucVu(string tenChucVu) {
            return base.Channel.IdChucVu(tenChucVu);
        }
        
        public System.Threading.Tasks.Task<int> IdChucVuAsync(string tenChucVu) {
            return base.Channel.IdChucVuAsync(tenChucVu);
        }
        
        public System.Data.DataTable OneRecord(string tblBang, string sqlString) {
            return base.Channel.OneRecord(tblBang, sqlString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> OneRecordAsync(string tblBang, string sqlString) {
            return base.Channel.OneRecordAsync(tblBang, sqlString);
        }
        
        public int IDTonGiao(string tenTonGiao) {
            return base.Channel.IDTonGiao(tenTonGiao);
        }
        
        public System.Threading.Tasks.Task<int> IDTonGiaoAsync(string tenTonGiao) {
            return base.Channel.IDTonGiaoAsync(tenTonGiao);
        }
        
        public System.Data.DataTable LayDiaChi(string idxa) {
            return base.Channel.LayDiaChi(idxa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayDiaChiAsync(string idxa) {
            return base.Channel.LayDiaChiAsync(idxa);
        }
        
        public object LayGiaTriDon(string sqlString) {
            return base.Channel.LayGiaTriDon(sqlString);
        }
        
        public System.Threading.Tasks.Task<object> LayGiaTriDonAsync(string sqlString) {
            return base.Channel.LayGiaTriDonAsync(sqlString);
        }
        
        public System.Data.DataTable LayMotBang(string sqlString) {
            return base.Channel.LayMotBang(sqlString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LayMotBangAsync(string sqlString) {
            return base.Channel.LayMotBangAsync(sqlString);
        }
        
        public int UpdateTinDo(
                    string idTinDo, 
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu) {
            return base.Channel.UpdateTinDo(idTinDo, phapDanh, hodemTheDanh, tenTheDanh, ngaySinh, gioiTinh, danToc, queQuan, diaChi, taiChinh, sucKhoe, tcTichCuc, tcNguyHiem, hinhAnh, matDoi, matDao, hdCaNhan, hdToChuc, idChucSac, idCoSo, daXoa, ngayVaoTonGiao, idChucVu);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTinDoAsync(
                    string idTinDo, 
                    string phapDanh, 
                    string hodemTheDanh, 
                    string tenTheDanh, 
                    System.DateTime ngaySinh, 
                    string gioiTinh, 
                    string danToc, 
                    string queQuan, 
                    string diaChi, 
                    string taiChinh, 
                    string sucKhoe, 
                    string tcTichCuc, 
                    string tcNguyHiem, 
                    string hinhAnh, 
                    string matDoi, 
                    string matDao, 
                    string hdCaNhan, 
                    string hdToChuc, 
                    int idChucSac, 
                    int idCoSo, 
                    int daXoa, 
                    System.DateTime ngayVaoTonGiao, 
                    int idChucVu) {
            return base.Channel.UpdateTinDoAsync(idTinDo, phapDanh, hodemTheDanh, tenTheDanh, ngaySinh, gioiTinh, danToc, queQuan, diaChi, taiChinh, sucKhoe, tcTichCuc, tcNguyHiem, hinhAnh, matDoi, matDao, hdCaNhan, hdToChuc, idChucSac, idCoSo, daXoa, ngayVaoTonGiao, idChucVu);
        }
    }
}
