//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_quan_ly_ton_giao.tblTinDo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tblTinDo.tblTinDoSoap")]
    public interface tblTinDoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSTinDo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HienThiDSTinDo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HienThiDSTinDo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSTinDoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tblTinDoSoapChannel : service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tblTinDoSoapClient : System.ServiceModel.ClientBase<service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap>, service_quan_ly_ton_giao.tblTinDo.tblTinDoSoap {
        
        public tblTinDoSoapClient() {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblTinDoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tblTinDoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable HienThiDSTinDo() {
            return base.Channel.HienThiDSTinDo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HienThiDSTinDoAsync() {
            return base.Channel.HienThiDSTinDoAsync();
        }
    }
}
